name: Setup Infrastructure
on:
  push:
    branches:
      - main
      - develop
jobs:
  test-infra:
    runs-on: ubuntu-latest
    env:
      TF_VAR_AWS_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
      TF_VAR_AWS_SECRET_ACCESS: ${{ secrets.TF_VAR_AWS_SECRET_ACCESS }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.7'
      - name: Install Modules
        working-directory: test
        run: go mod download
      - name: Run Tests
        working-directory: test
        run: go test -v -timeout 30m